### ISSUE TITLE
JUnit Test Plan 的输入参数 functionBody 中的标记符号应该区分参数，不能假设参数是按顺序的。即 CIT cit= new CIT(&#) 中的 &# 可能是 parameter 1 也可能是 parameter 2

### ISSUE THREAD

**Issue by lejinWang** [GIST-NJU/CitHub#1]
不太明白，顺序不是填写真实值时就固定了吗？一条测试用例默认就是顺序执行的.
明白了

**Comment by waynedd** [comment]
顺序不是固定的，CA里面任意两列都可以相互替换，我们不能要求在组合测试模型中必须“按某种顺序”给出参数名称及取值。

例如三个参数及取值：
OS = {Windows, Linux}
Browser = {Firefox, Chrome, QQ}
Num = {0, 1, 2}

模版可能是
CIT cit = new cit(OS)
cit.setNum(Num);
cit.runBrowser(Browser);

在代码中出现的顺序未必就是参数声明中的顺序
